### ISSUE TITLE
Code in playground still can't be compiled

### ISSUE THREAD

**Issue by igordonxiao** [maierfelix/Hevia#2]
version: 0.0.5

![2016-07-07 9 44 55](https://cloud.githubusercontent.com/assets/2564493/16640028/6d806ad6-4427-11e6-872d-f9980116ce2a.png)

**Comment by maierfelix** [comment]
When the parser becomes more or less stable, the compiler, type inferencer and generator will be re-implemented. Each time the parser's ast syntax get improved or changed, the type inferencer and generator have to be updated, too. So thats the reason, why it doesn't work, right now.
